apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: zuri-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "zuriapp-secrets"
        objectType: "secretsmanager"
  secretObjects:
    - secretName: zuri-k3s-secret
      type: Opaque
      data:
        - objectName: "API_SECRET_KEY"
          key: API_SECRET_KEY
        - objectName: "STORE_NAME"
          key: STORE_NAME
